
import { config } from "dotenv";
config();
 const {
  PORT,
  CLIENT_ORIGIN,
  REDIS_URI,
  MONGODB_URI,
  NODE_ENV,
  JWT_SECRET,
  JWT_EXPIRES_IN,
  REFRESH_SECRET,
  REFRESH_EXPIRES_IN,
  DB_PROVIDER = "mongoose",
  REDIS_QUEUE_URI = REDIS_URI,
  STORAGE_PROVIDER,
  CLOUDINARY_SECRET,
  CLOUDINARY_API_KEY,
  CLOUDINARY_CLOUD_NAME,
  R2_ACCOUNT_ID,
  R2_ACCESS_KEY,
  R2_SECRET_KEY,
  R2_BUCKET,
R2_PUBLIC_URL
} = process.env;


export const _config = {
  PORT,
  CLIENT_ORIGIN,
  REDIS_URI,
  MONGODB_URI,
  NODE_ENV,
  JWT_SECRET,
  JWT_EXPIRES_IN,
  REFRESH_SECRET,
  REFRESH_EXPIRES_IN,
  DB_PROVIDER,
  REDIS_QUEUE_URI,
  STORAGE_PROVIDER,
  CLOUDINARY_SECRET,
  CLOUDINARY_API_KEY,
  CLOUDINARY_CLOUD_NAME,
  R2_ACCOUNT_ID,
  R2_ACCESS_KEY,
  R2_SECRET_KEY,
  R2_BUCKET,
  R2_PUBLIC_URL

}
